import Head from 'next/head';
import styles from '../styles/header.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>
                    Merit Education clone ingliz tili o&#039;quv markazi haqida
                    || Eng zo&#039;r o&#039;quv markaz
                </title>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
                    rel="stylesheet"
                />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Salom hammaga</h1>
            </div>
        </div>
    );
}
