import Head from 'next/head';
import styles from '../styles/header.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>
                    Merit Education clone ingliz tili o&#039;quv markazi haqida
                    || Eng zo&#039;r o&#039;quv markaz
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Salom hammaga</h1>
            </div>
        </div>
    );
}
